# Generated by Django 5.0.4 on 2024-04-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('Resolved', 'Resolved'), ('In Progress', 'In Progress')], default='In Progress', max_length=20),
        ),
    ]
